name: Stage the app

on: 
  pull_request:
    types: [labeled]

env:
  DOCKER_IMAGE_NAME: pandey-mithun-azure-ttt
  IMAGE_REGISTRY-URL: docker.pkg.github.com
  AZURE_WEBAPP_NAME: pandey-mithun-ttt-app

jobs:
  build:
    runs-on: ubuntu-latest
    
    if: contains(github.event.pull_request.labels.*.name, 'stage')
